version: "3"

services:
  app:
    container_name: "php-apache"
    build: ./app/
    volumes:
      - ./app/html:/var/www/html
    ports:
      - "80:80"
  mysql:
    container_name: "mysql"
    build: ./db/
    ports:
      - "3306:3306"
    tty: true
